services:

  frontend:
    image: markl90001/quirknotes_frontend:latest
    ports:
      - "3000:80"

  backend:
    image: markl90001/quirknotes_backend:latest
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"